stages:
  - containerization

variables:
  APPLICATION_NAME: annotation-tool

containerization:
  stage: containerization
  script:
    - docker build -t ${CONTAINER_REGISTRY}/${APPLICATION_NAME} .
    - docker push ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
    - docker image rm ${CONTAINER_REGISTRY}/${APPLICATION_NAME}
