stages:
  - build

image: moreillon/ci-dind:4bca50d7
services:
  - name: docker:19.03.12-dind

variables:
  APPLICATION_NAME: annotation-tool
  CONTAINER_REGISTRY_URL: 732469118990.dkr.ecr.ap-northeast-1.amazonaws.com
  CONTAINER_IMAGE: ${CONTAINER_REGISTRY_URL}/${APPLICATION_NAME}
  CONTAINER_IMAGE_TAGGED: ${CONTAINER_IMAGE}:${CI_COMMIT_SHORT_SHA}

build:
  stage: build
  only:
    - master
  tags:
    - dind
  before_script:
    # Create repository if needed
    - >
      aws ecr create-repository --repository-name ${APPLICATION_NAME}
      || echo "Repository might have already existed"
    # Log in to the registry (AWS credentials are stored as GitLab env variables)
    - >
      aws ecr get-login-password
      | docker login
      --username AWS
      --password-stdin
      ${CONTAINER_REGISTRY_URL}
  script:
    # Build the container image
    - docker build -t ${CONTAINER_IMAGE} .
    - docker tag ${CONTAINER_IMAGE} ${CONTAINER_IMAGE_TAGGED}
    # Build and push container image to registry
    - docker push ${CONTAINER_IMAGE}
    - docker push ${CONTAINER_IMAGE_TAGGED}